apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-sonar
    namespace: flux-system
  resources:
    - helm-repo.yaml
    - postgres/postgres-helmrelease.yaml
    - sonarqube/sonarqube-helmrelease.yaml
    - ingress/sonar-ingress.yaml

