apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: default
spec:
  releaseName: sonarqube
  chart:
    spec:
      chart: bitnami/sonarqube  # Ensure you specify the correct repository and chart name
      version: 6.0.0            # Use the chart version you want to deploy
      sourceRef:
        kind: HelmRepository
        name: bitnami            # Name of the Helm repository
        namespace: flux-system
  values:
    postgresql:
      enabled: true
      postgresqlDatabase: sonarqube
      postgresqlUsername: sonar
      postgresqlPassword:
        secretKeyRef:
          name: postgres-password
          key: password
    service:
      type: ClusterIP
