apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: default
spec:
  releaseName: sonarqube
  chart:
    spec:
      chart: sonarqube
      sourceRef:
        kind: HelmRepository
        name: sonarqube
        namespace: flux-system
  values:
    postgresql:
      enabled: true
      postgresqlDatabase: sonarqube
      postgresqlUsername: sonar
      postgresqlPassword:
        secretKeyRef:
          name: postgres-password
          key: password
    service:
      type: ClusterIP
